Correct error in docs for Read and Write opcodes.
tokio-rs/io-uring pull request #112
Opened 2021-09-16 08:58 UTC by zethra

Fixes #111

2021-09-16 09:27 UTC, zethra commented
I've added a second commit clarifying how error codes are handled.

2021-09-17 03:07 UTC, quininer requested changes

2021-09-17 03:07 UTC, quininer commented on src/opcode.rs
> +    /// Read from a file descriptor, mostly equivalent to `pread(2)`.
Maybe we can follow the latest manpage of liburing.

2021-09-17 03:07 UTC, quininer commented on src/cqueue.rs
> +    /// Except, in an error case many system calls would return `-1` and set errno.
I believe that the meaning of `result` is not universal, and the meaning of `result` of each opcode may be different. We should mention this here and describe the meaning of `result` in each opcode document.

2021-09-17 03:14 UTC, zethra commented
I submitted an issue to liburing as well and they updated their docs so I'll update this PR what the language they used.

2021-09-22 08:18 UTC, zethra commented
I updated the comments based on the revised liburing docs.

2021-11-30 16:00 UTC, closed without merging