opcode: add "fixed file" support to openat, openat2 and close
tokio-rs/io-uring pull request #181
Opened 2023-02-10 13:31 UTC by FrankReh

Following the model for the file_index builder method set in #179.

Addresses three of the opcodes highlighted in #178.

2023-02-10 13:31 UTC, FrankReh commented
Still a wip while unit tests are missing.

2023-02-13 14:04 UTC, FrankReh commented
@quininer I think @lucab is correct in his comment in
- #182 

Do you agree the opcode::Close is better taking a Fixed FD 1st parameter, an no optional file_index method? Would that make it a breaking semver change though?

2023-02-14 02:00 UTC, quininer commented
Yes, we should use `UseFixed`, I don't think it's a breaking change. I intentionally designed these two sealed traits so that `impl UseFd` can be changed to `impl UseFixed` at any time.

2023-02-14 02:01 UTC, quininer requested changes
about close opcode

2023-02-14 05:33 UTC, quininer approved these changes
LGTM

2023-02-14 11:23 UTC, merged