Add {squeue, cqueue}::Mut
tokio-rs/io-uring pull request #72
Opened 2021-02-16 20:41 UTC by Kestrer

- The name `Mut` is free to be changed, I chose it to be used with code like `cqueue::Mut`, but I'll admit it doesn't give very good docs and having two types of the same name can be confusing.
- I renamed `submission`/`completion` to `submission_mut`/`completion_mut` as they return `Mut`s, and also it would be nice to have methods that return `&SubmissionQueue`s and `&CompletionQueue`s in the future.
- `Mut::reborrow` is free to be changed, as an alternative it could be called `as_mut`.
- I also removed `AvailableQueue` in favour of using the atomic ops directly, since they're cheap.

2021-02-16 23:44 UTC, quininer commented
iai bench seems to have a performance regression.

before:
```
bench_io_uring
  Instructions:                3588 (No change)
  L1 Accesses:                 5661 (No change)
  L2 Accesses:                   18 (No change)
  RAM Accesses:                  80 (No change)
  Estimated Cycles:            8551 (No change)

bench_io_uring_batch
  Instructions:                2968 (No change)
  L1 Accesses:                 4546 (No change)
  L2 Accesses:                   22 (No change)
  RAM Accesses:                  91 (No change)
  Estimated Cycles:            7841 (No change)
```

after:
```
bench_io_uring
  Instructions:                5900 (+64.43701%)
  L1 Accesses:                10404 (+83.78378%)
  L2 Accesses:                   15 (-16.66667%)
  RAM Accesses:                  60 (-25.00000%)
  Estimated Cycles:           12579 (+47.10560%)

bench_io_uring_batch
  Instructions:                4406 (+48.45013%)
  L1 Accesses:                 7320 (+61.02068%)
  L2 Accesses:                   25 (+13.63636%)
  RAM Accesses:                  96 (+5.494505%)
  Estimated Cycles:           10805 (+37.80130%)
```

2021-02-16 23:57 UTC, quininer requested changes

2021-02-16 23:57 UTC, quininer commented on src/squeue.rs
> +pub struct Mut<'a>(pub(crate) &'a mut SubmissionQueue);
I think we can keep the name of `SubmissionQueue` and make the original `SubmissionQueue` a private structure. to avoid excessive API changes.

2021-02-16 23:57 UTC, quininer commented on src/lib.rs
> +    pub fn submission_mut(&mut self) -> squeue::Mut<'_> {
I think it can keep its original name.

2021-02-16 23:57 UTC, quininer commented on src/squeue.rs
> +    pub fn reborrow(&mut self) -> Mut<'_> {
:heart:

2021-02-16 23:57 UTC, quininer commented on src/squeue.rs
> -impl AvailableQueue<'_> {
I still want to keep `AvailableQueue`, which has better performance in theory and is not complicated.

2021-02-17 06:43 UTC, Kestrer commented
One of the reasons I decided to use `submission_mut` and `Mut` is that I would like to support using the queues from shared references to the io_uring instance. For example currently it's not possible to check whether the kernel thread needs waking up (`SubmissionQueue::need_wakeup`) from an `&IoUring`, when it could be if we provided `fn submission(&self) -> &SubmissionQueue` as well as `fn submission(&mut self) -> &mut SubmissionQueue`. 

Also, if we later exposed an extra-`unsafe` API for pushing to an `&SubmissionQueue`, it would allow `ownedsplit` to be implemented entirely using the public API of the library, which is good for code readability and would give users the opportunity of making their own similar data structures.

2021-02-17 08:11 UTC, quininer commented
Returning `&SubmissionQueue` sounds easy to be abused. If we want to know whether we need to wake up, we can expose the `sq_need_wakeup` method of `Submitter`.

I would rather avoid interior mutability.

2021-02-17 08:27 UTC, Kestrer commented
> Returning `&SubmissionQueue` sounds easy to be abused.

Is it? What in particular are you thinking of?

> we can expose the sq_need_wakeup method of Submitter.

But it's not just this - it is potentially useful to access _all_ the concurrently accessible properties of the sq and cq from a shared reference, and I wouldn't like to duplicate all the methods.

> I would rather avoid interior mutability.

It wouldn't actually require interior mutability I don't think - we have a `*mut` pointer, so the shared-push methods can just write to that exactly as the existing ones do. The code would be identical, it would just take &self instead of &mut self.

2021-02-17 08:35 UTC, quininer commented
> it is potentially useful to access all the concurrently accessible properties of the sq and cq from a shared reference, and I wouldn't like to duplicate all the methods.

I really don't think there will be many repetitive methods. And I don't know which scenes need to access them at the same time.

> The code would be identical, it would just take &self instead of &mut self.

This is the definition of interior mutability.

2021-02-17 11:54 UTC, Kestrer commented
Ok, this new design incorporates the performance advantages of an `AvailableQueue`, and avoids the complexity of having both `{Submission, Completion}Queue` and `Mut` - there is only `{Submission, Completion}Queue` in the API. I have not implemented the ability to get sq/cq flags without mutable access to the `IoUring`.

2021-02-17 12:09 UTC, quininer approved these changes
This looks great, thank you very much!

2021-02-17 12:10 UTC, merged